#单机
server:
  port: 8011

spring:
  application:
    name: BBB
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.137.132:9411
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url: http://localhost:${server.port}
    instance-id: BBB-1:${server.port}
    

##高可用
#server:
#  port: 8011
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
#  instance:
#    appname: BBB
#    status-page-url: http://localhost:${server.port}
#    instance-id: BBB-1:${server.port}